name: Build, Lint, and Test
on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]


jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Run eslint
        run: npm run lint

      - name: Run tests
        run: npm run test
